spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017
      database: transaction
resilience4j:
  bulkhead:
    instances:
      gitbulkhead:
        maxConcurrentCalls: 2
  circuitbreaker:
    instances:
      github:
        registerHealthIndicator: true
        slidingWindowSize: 3
        slidingWindowType: COUNT_BASED
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 50ms
        ignoreExceptions:
          - br.com.sicredi.sicrediresilience4j.exception.DomainException
  timelimiter:
    instances:
      githubTimelimiter:
        timeoutDuration: 50ms
        cancelRunningFuture: true




management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans, loggers, health
  endpoint:
    health:
      show-details: always

twitter:
  url: https://api.github.com